// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://orkogyslfpcpfelevjkb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ya29neXNsZnBjcGZlbGV2amtiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4NTQ4MjksImV4cCI6MjA2MDQzMDgyOX0.XTwFrFV2Dt7xaF9ButxKp8p94zrrAGvTR1Ud3yeL4bY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});